"""Add full EMR patient fields

Revision ID: e546a4069367
Revises: b10828211d0b
Create Date: 2025-11-17 23:29:59.180184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e546a4069367'
down_revision: Union[str, None] = 'b10828211d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_medications', sa.String(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('current_medications')
        batch_op.drop_column('allergies')
        batch_op.drop_column('medical_history')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
